### PR TITLE
Update EmirhanUcan.yar

### PR DESCRIPTION
**Pull request by ghost**
add double quotes to 'author'

### CODE REVIEW

**Comment by HydraDragonAntivirus** [comment]
Actually this project currently dead I working on Rust and Xylent python right now. If you want I can upload latest version of Xylent.

**Comment by ghost** [comment]
Yes, please! thank you!

**Comment by HydraDragonAntivirus** [comment]
Ok. I'm going to share it today.

**Comment by HydraDragonAntivirus** [comment]
https://mega.nz/file/WhBRyBxA#vhGayaWmTZNeb57ijiAUuFWlRBFty07FSShrBmxT5-U Databases. Source code: 
https://github.com/HydraDragonAntivirus/Xylent

**Pull request merged**
